# Site settings
title: Daniel Perez
meta_title: Daniel Perez website
subtitle: 'software engineer interested in programming languages and functional programming'
description: 'blog about programming'
url: 'http://tuvistavie.com'
baseurl: '/'
google_analytics: 'UA-40262798-2'
disqus_shortname: 'tuvistavie'

author:
  name: 'Daniel Perez'
  email: tuvistavie@gmail.com
  twitter_username: tuvistavie
  facebook_username: tuvistavie
  github_username:  tuvistavie
  linkedin_username:  tuvistavie

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  autolink: true

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
