# Site settings
title: Daniel Perez
meta_title: Daniel Perez website
subtitle: 'software engineer interested in programming languages and functional programming'
description: 'personal homepage of Daniel Perez'
url: 'https://daniel.perez.sh'
baseurl: '/'
google_analytics: 'UA-40262798-2'
disqus_shortname: 'tuvistavie'
fb_app_id: '235454057192512'

author:
  name: 'Daniel Perez'
  email: "[first]@[last].sh"
  twitter_username: tuvistavie
  facebook_username: danhper
  github_username:  danhper
  linkedin_username:  danhper
  avatar: profile-coffee-2016-small.jpg

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      footer: true

# Build settings
destination: _site
paginate: 10
paginate_path: /blog/page:num/
permalink: blog/:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  autolink: true

plugins: ['jekyll-paginate', 'jekyll-redirect-from']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
include: ['.well-known']

sass:
  sass_dir: _sass
