default: &default
  adapter: postgresql
  encoding: unicode
  username: daniel
  pool: 5
  template: template0

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  username: tuvistavie_blog
  host: <%= ENV['BLOG_DATABASE_ENDPOINT'] || 'localhost' %>
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
